import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
	const { data: session, status } = useSession();

	return (
		<>
			<Head>
				<title>Blog Tree | Home</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex flex-col items-center justify-center h-screen w-screen bg-neutral-800 text-slate-50 font-raleway">
				<header className="flex bg-neutral-800 border-b border-neutral-600/50 py-2 px-4 lg:px-[10vw] justify-end w-full fixed top-0">
					<nav>
						{status === "unauthenticated" && (
							<div>
								<button
									onClick={() => signIn()}
									className="inline-flex py-1 px-3 rounded text-sm bg-blue-600 hover:bg-blue-700 focus:ring-2 focus:ring-indigo-600 focus:ring-offset-1 tracking-wider focus:outline-none font-bold transition-colors ease-out"
								>
									Login
								</button>
							</div>
						)}
						{status === "authenticated" && (
							<div className="space-x-6 flex items-center">
								<span className="font-bold text-sm flex items-center gap-2">
									<Image
										src={session.user?.image as string}
										alt={session.user?.name as string}
										width={25}
										height={25}
										className="rounded-full"
									/>
									{session.user?.name}
								</span>
								<button
									onClick={() => signOut()}
									className="inline-flex py-1 px-3 rounded text-sm bg-red-600 hover:bg-red-700 focus:ring-2 focus:ring-indigo-600 focus:ring-offset-1 tracking-wider focus:outline-none font-bold transition-colors ease-out"
								>
									Logout
								</button>
							</div>
						)}
						{status === "loading" && (
							<div>
								<button className="inline-flex py-1 px-3 rounded text-sm bg-amber-600 hover:bg-amber-700 focus:ring-2 focus:ring-indigo-600 focus:ring-offset-1 tracking-wider focus:outline-none font-bold transition-colors ease-out animate-pulse">
									Loading...
								</button>
							</div>
						)}
					</nav>
				</header>
				<h1>Hello world</h1>
			</main>
		</>
	);
};

export default Home;
