import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "$/components/Navbar";
// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Blog Tree | Home</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex flex-col items-center justify-center h-screen w-screen bg-neutral-800 text-slate-50 font-raleway">
				<Navbar />
				<h1>Hello world</h1>
			</main>
		</>
	);
};

export default Home;
