import Head from "next/head";
import { ReactNode } from "react";
import Navbar from "./Navbar";

interface LayoutProps {
	children: ReactNode;
	title?: string;
}

const Layout = ({ children, title }: LayoutProps) => {
	return (
		<>
			<Head>
				<title>Blog Tree | {title}</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex flex-col items-center pt-28 h-screen w-screen bg-neutral-100 text-neutral-900 dark:bg-neutral-800 dark:text-neutral-50 font-inter overflow-y-scroll pb-4 transition-colors ease-in">
				<Navbar />
				{children}
			</main>
		</>
	);
};

export default Layout;
